### ISSUE TITLE
JavaScript: Conflict with eslinst Google rules

### ISSUE THREAD

**Issue by dandv** [mbrukman/autogen#16]
Running eslint produces the [spaced-comment](http://eslint.org/docs/rules/spaced-comment) error:

> Expected space or tab after '//' in comment  spaced-comment

Here's the [linting rule](https://github.com/google/eslint-config-google/blob/master/index.js#L274).

One [workaround](https://github.com/dandv/imagecapture/commit/fb75283e53a3ace7938b53c26923db0421152e53) would be to change that rule to allow for a `/` exception:

```
"spaced-comment": ["error", "always", { "markers": ["/"] }]
```

**Comment by addyosmani** [comment]
> One workaround would be to change that rule to allow for a / exception:

I would be in favor of this change. If there are recommendations/patches folks would like to propose for the eslint google ruleset, please feel free to comment on the issue Dan linked to above.

**Comment by mbrukman** [comment]
I'm going to fix this in autogen by making the line-of-comment-characters optional, which will also address another reported issue #12 so you don't need to change eslint on autogen's account.

**Comment by mbrukman** [comment]
I submitted a change that, in theory, should make the new output compliant with eslint. Please take a look and let me know if it's now OK and we can close this issue. Thanks for the feedback!

**Comment by mbrukman** [comment]
@dandv — assigning the issue to you to verify whether the change I made addresses your concerns.

**Comment by mbrukman** [comment]
Closing this issue as I believe it has been addressed with making the comment line optional (and off by default). If there are any other issues, please add a comment and reopen.
