### ISSUE TITLE
Add support for ipynb file

### ISSUE THREAD

**Issue by wangtz** [mbrukman/autogen#57]
IPython notebook is a popular tool for machine learning developer/researcher. Would be great to add support for this. 

Thanks,

**Comment by wangtz** [comment]
.ipynb file represents a series of Python code blocks. I'm suggesting to add license on top of the first code block so that it's visible to users. I don't think normal users would look into the JSON source code.

**Comment by wangtz** [comment]
Looks good. Thanks. :-)

I see that you added a text block instead of code block for these comments. I'm fine with either.

**Comment by wangtz** [comment]
Eh. I didn't find any related commit. Most recent one is adding .bat support. Do you mean a pull request?

**Comment by mbrukman** [comment]
@wangtz -- it's in a branch on this repository; you can see the preview using the same links as above (I modified a sample file in-place). If you want to see what it looks like in practice, see the `ipynb-support` in this repo, it's not a PR yet as I'm still iterating on it.

**Comment by wangtz** [comment]
Ah I see. I had a quick look at your ipynb.py but didn't quite understand the logic. Are you replacing the  metadata section when a header is added. 

I thought the metadata section is provided by the users (e.g. they may not be using PYthon3), and all we need to in this case is to prepend an element in cells.source.

What do you think?

**Comment by mbrukman** [comment]
@wangtz — without the metadata section, the notebook didn't load in the tools I tried it in, it just failed, so it wasn't usable. How would a user get to a usable state if the boilerplate we generate (without the metadata section) is insufficient to load into a notebook viewer?

I presume the metadata should be modifiable by users after the notebook is loaded.

Here's my sample file:
https://github.com/mbrukman/autogen/blob/ipynb-support/tests/testdata/sample.ipynb

Do you want to try it out with your notebook environment, and then delete the metadata section and see if it still loads for you?

**Comment by mbrukman** [comment]
I've merged https://github.com/mbrukman/autogen/pull/66 to add support for Jupyter notebooks.
