### ISSUE TITLE
cmdline option -i doesn't preserve permissions

### ISSUE THREAD

**Issue by tadhunt** [mbrukman/autogen#6]
Bug:
* Start with `foo.sh` file checked into git with permissions `0755`
* Run `autogen.sh -i [...] foo.sh`
* Issue: permissions changed to `0644`

Expected behavior: 
* Permissions are unaffected by addition of copyright comment to file

**Comment by mbrukman** [comment]
Good catch, @tadhunt!

The way this feature was implemented is by writing to a new file and then moving the file over to the old file, so the new file is being created with your default umask and hence may be different from the original file.

Prior moving the new temp file to the original location, we should ensure that the permissions are transferred. I'll look into this.

**Comment by mbrukman** [comment]
I believe this issue has been fixed. Please try it out and let me know if you are still seeing any discrepancies with file permissions.
